### ISSUE TITLE
'PublicData' object has no attribute 'split_data'

### ISSUE THREAD

**Issue by upretiramesh** [interpretml/DiCE#112]
Hi, 

I am following the tutorial posted in
[](https://towardsdatascience.com/dice-diverse-counterfactual-explanations-for-hotel-cancellations-762c311b2c64)
When I tried to split the data, I got PublicData object has no attribute 'split_data'. Is this because it has removed in the new version? if yes then how can I split the data. I appreciate your help. 

![Selection_332](https://user-images.githubusercontent.com/6251101/111766414-cf125a80-88a5-11eb-8655-3c8031d4d260.png)

**Comment by amit-sharma** [comment]
Hi @upretiramesh yeah, the `split_data` has been removed in the new version. DiCE handling the data splitting was often a problem with pre-trained ML models where the data splitting had already been done. We did update the notebooks with this change--can you share the link where you found this line?

You can split the data using the standard `train_test_split` from sklearn. Check out this notebook for an example. https://github.com/interpretml/DiCE/blob/master/docs/source/notebooks/DiCE_getting_started.ipynb

**Comment by upretiramesh** [comment]
Hi @amit-sharma thank you for your response.
