### ISSUE TITLE
DiceRandom is not able to handle case when requested counterfactuals is zero

### ISSUE THREAD

**Issue by gaugup** [interpretml/DiCE#117]
exp = Dice(d, m, method="random")
query_instance = x_train[1:2]
e1 = exp.generate_counterfactuals(query_instance, **total_CFs=0**, desired_range=None,desired_class="opposite",
                                   permitted_range=None, features_to_vary="all")
e1.visualize_as_dataframe(show_only_changes=True)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-9ea176bfa08a> in <module>
      2 query_instance = x_train[1:2]
      3 e1 = exp.generate_counterfactuals(query_instance, total_CFs=0, desired_range=None,desired_class="opposite",
----> 4                                    permitted_range=None, features_to_vary="all")
      5 e1.visualize_as_dataframe(show_only_changes=True)

c:\users\gaugup\documents\github\dice\dice_ml\explainer_interfaces\explainer_base.py in generate_counterfactuals(self, query_instances, total_CFs, desired_class, desired_range, permitted_range, features_to_vary, stopping_threshold, posthoc_sparsity_param, posthoc_sparsity_algorithm, verbose, **kwargs)
     87                     posthoc_sparsity_algorithm=posthoc_sparsity_algorithm,
     88                     verbose=verbose,
---> 89                     **kwargs)
     90             cf_examples_arr.append(res)
     91         return CounterfactualExplanations(cf_examples_list=cf_examples_arr)

c:\users\gaugup\documents\github\dice\dice_ml\explainer_interfaces\dice_random.py in _generate_counterfactuals(self, query_instance, total_CFs, desired_range, desired_class, permitted_range, features_to_vary, stopping_threshold, posthoc_sparsity_param, posthoc_sparsity_algorithm, sample_size, random_seed, verbose)
    136                 cfs_df = cfs_df.sample(total_CFs)
    137             cfs_df.reset_index(inplace=True, drop=True)
--> 138             self.cfs_pred_scores = self.predict_fn(cfs_df)
    139             cfs_df[self.data_interface.outcome_name] = self.get_model_output_from_scores(self.cfs_pred_scores)
    140 

c:\users\gaugup\documents\github\dice\dice_ml\explainer_interfaces\dice_random.py in predict_fn(self, input_instance)
    225     def predict_fn(self, input_instance):
    226         """prediction function"""
--> 227         return self.model.get_output(input_instance)

c:\users\gaugup\documents\github\dice\dice_ml\model_interfaces\base_model.py in get_output(self, input_instance)
     38         input_instance = self.transformer.transform(input_instance)
     39         if self.model_type == "classifier":
---> 40             return self.model.predict_proba(input_instance)
     41         else:
     42             return self.model.predict(input_instance)

~\Anaconda3\envs\env1\lib\site-packages\sklearn\utils\metaestimators.py in <lambda>(*args, **kwargs)
    118 
    119         # lambda, but not partial, allows help() to work with update_wrapper
--> 120         out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
    121         # update the docstring of the returned function
    122         update_wrapper(out, self.fn)

~\Anaconda3\envs\env1\lib\site-packages\sklearn\pipeline.py in predict_proba(self, X)
    472         Xt = X
    473         for _, name, transform in self._iter(with_final=False):
--> 474             Xt = transform.transform(Xt)
    475         return self.steps[-1][-1].predict_proba(Xt)
    476 

~\Anaconda3\envs\env1\lib\site-packages\sklearn\compose\_column_transformer.py in transform(self, X)
    563                 "data given during fit."
    564             )
--> 565         Xs = self._fit_transform(X, None, _transform_one, fitted=True)
    566         self._validate_output(Xs)
    567 

~\Anaconda3\envs\env1\lib\site-packages\sklearn\compose\_column_transformer.py in _fit_transform(self, X, y, func, fitted)
    442                     message=self._log_message(name, idx, len(transformers)))
    443                 for idx, (name, trans, column, weight) in enumerate(
--> 444                         self._iter(fitted=fitted, replace_strings=True), 1))
    445         except ValueError as e:
    446             if "Expected 2D array, got 1D array instead" in str(e):

~\Anaconda3\envs\env1\lib\site-packages\joblib\parallel.py in __call__(self, iterable)
   1027             # remaining jobs.
   1028             self._iterating = False
-> 1029             if self.dispatch_one_batch(iterator):
   1030                 self._iterating = self._original_iterator is not None
   1031 

~\Anaconda3\envs\env1\lib\site-packages\joblib\parallel.py in dispatch_one_batch(self, iterator)
    845                 return False
    846             else:
--> 847                 self._dispatch(tasks)
    848                 return True
    849 

~\Anaconda3\envs\env1\lib\site-packages\joblib\parallel.py in _dispatch(self, batch)
    763         with self._lock:
    764             job_idx = len(self._jobs)
--> 765             job = self._backend.apply_async(batch, callback=cb)
    766             # A job can complete so quickly than its callback is
    767             # called before we get here, causing self._jobs to

~\Anaconda3\envs\env1\lib\site-packages\joblib\_parallel_backends.py in apply_async(self, func, callback)
    204     def apply_async(self, func, callback=None):
    205         """Schedule a func to be run"""
--> 206         result = ImmediateResult(func)
    207         if callback:
    208             callback(result)

~\Anaconda3\envs\env1\lib\site-packages\joblib\_parallel_backends.py in __init__(self, batch)
    568         # Don't delay the application, to avoid keeping the input
    569         # arguments in memory
--> 570         self.results = batch()
    571 
    572     def get(self):

~\Anaconda3\envs\env1\lib\site-packages\joblib\parallel.py in __call__(self)
    251         with parallel_backend(self._backend, n_jobs=self._n_jobs):
    252             return [func(*args, **kwargs)
--> 253                     for func, args, kwargs in self.items]
    254 
    255     def __reduce__(self):

~\Anaconda3\envs\env1\lib\site-packages\joblib\parallel.py in <listcomp>(.0)
    251         with parallel_backend(self._backend, n_jobs=self._n_jobs):
    252             return [func(*args, **kwargs)
--> 253                     for func, args, kwargs in self.items]
    254 
    255     def __reduce__(self):

~\Anaconda3\envs\env1\lib\site-packages\sklearn\utils\fixes.py in __call__(self, *args, **kwargs)
    220     def __call__(self, *args, **kwargs):
    221         with config_context(**self.config):
--> 222             return self.function(*args, **kwargs)

~\Anaconda3\envs\env1\lib\site-packages\sklearn\pipeline.py in _transform_one(transformer, X, y, weight, **fit_params)
    731 
    732 def _transform_one(transformer, X, y, weight, **fit_params):
--> 733     res = transformer.transform(X)
    734     # if we have a weight for this transformer, multiply output
    735     if weight is None:

~\Anaconda3\envs\env1\lib\site-packages\sklearn\pipeline.py in _transform(self, X)
    558         Xt = X
    559         for _, _, transform in self._iter():
--> 560             Xt = transform.transform(Xt)
    561         return Xt
    562 

~\Anaconda3\envs\env1\lib\site-packages\sklearn\preprocessing\_data.py in transform(self, X, copy)
    884                                 accept_sparse='csr', copy=copy,
    885                                 estimator=self, dtype=FLOAT_DTYPES,
--> 886                                 force_all_finite='allow-nan')
    887 
    888         if sparse.issparse(X):

~\Anaconda3\envs\env1\lib\site-packages\sklearn\base.py in _validate_data(self, X, y, reset, validate_separately, **check_params)
    419             out = X
    420         elif isinstance(y, str) and y == 'no_validation':
--> 421             X = check_array(X, **check_params)
    422             out = X
    423         else:

~\Anaconda3\envs\env1\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
     61             extra_args = len(args) - len(all_args)
     62             if extra_args <= 0:
---> 63                 return f(*args, **kwargs)
     64 
     65             # extra_args > 0

~\Anaconda3\envs\env1\lib\site-packages\sklearn\utils\validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
    670                              " minimum of %d is required%s."
    671                              % (n_samples, array.shape, ensure_min_samples,
--> 672                                 context))
    673 
    674     if ensure_min_features > 0 and array.ndim == 2:

**ValueError: Found array with 0 sample(s) (shape=(0, 2)) while a minimum of 1 is required by StandardScaler.**

Testing with other Dice explainers, kdtree/genetic and it seems they handle this scenario much more gracefully.

**Comment by amit-sharma** [comment]
Added a PR for this. Can you review @gaugup ?
