### ISSUE TITLE
Getting the following error : "feature "" has a value outside the dataset"

### ISSUE THREAD

**Issue by noureini** [interpretml/DiCE#122]
When generating the counterfactual explanation, i'm getting an error related to a feature value which value is considered to be outside of the dataset. This is strange for me, since the variable is a dummy and is not allowed to vary. The variable name is not in the list of feature to vary. My target variable is continous. Perhaps i'm missing something, could someone help, please. 

Sincerely yours

**Comment by gaugup** [comment]
@noureini , could you please share some sample code or python stack trace?

Regards,

**Comment by noureini** [comment]
@gaugup, please find below the traceback 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-39-b20753a14def> in <module>
      2 #features_vary=list(filter(r.match, continuous_features_df_lait_cf))
      3 query_instances_lait = x_train[2:3]
----> 4 genetic_lait = exp_genetic_lait.generate_counterfactuals(query_instances_lait, 
      5                                                              total_CFs=2,
      6                                                              features_to_vary=['Positionnement: lait_vendu_par_sfp', 'has a value outside the dataset'],

~\anaconda3\lib\site-packages\dice_ml\explainer_interfaces\explainer_base.py in generate_counterfactuals(self, query_instances, total_CFs, desired_class, desired_range, permitted_range, features_to_vary, stopping_threshold, posthoc_sparsity_param, posthoc_sparsity_algorithm, verbose, **kwargs)
     82             #query_instances = query_instances.to_dict("records")
     83         for query_instance in query_instances_list:
---> 84             res = self._generate_counterfactuals(query_instance, total_CFs,
     85                     desired_class=desired_class,
     86                     desired_range=desired_range,

~\anaconda3\lib\site-packages\dice_ml\explainer_interfaces\dice_genetic.py in _generate_counterfactuals(self, query_instance, total_CFs, initialization, desired_range, desired_class, proximity_weight, diversity_weight, categorical_penalty, algorithm, features_to_vary, permitted_range, yloss_type, diversity_loss_type, feature_weights, stopping_threshold, posthoc_sparsity_param, posthoc_sparsity_algorithm, maxiterations, verbose)
    260         self.start_time = timeit.default_timer()
    261 
--> 262         features_to_vary = self.setup(features_to_vary, permitted_range, query_instance, feature_weights)
    263 
    264         # Prepares user defined query_instance for DiCE.

~\anaconda3\lib\site-packages\dice_ml\explainer_interfaces\explainer_base.py in setup(self, features_to_vary, permitted_range, query_instance, feature_weights)
    104         else: # compute the new ranges based on user input
    105             self.feature_range, feature_ranges_orig = self.data_interface.get_features_range(permitted_range)
--> 106         self.check_query_instance_validity(features_to_vary, permitted_range, query_instance, feature_ranges_orig)
    107 
    108         # check feature MAD validity and throw warnings

~\anaconda3\lib\site-packages\dice_ml\explainer_interfaces\explainer_base.py in check_query_instance_validity(self, features_to_vary, permitted_range, query_instance, feature_ranges_orig)
    114         for feature in self.data_interface.categorical_feature_names:
    115             if query_instance[feature].values[0] not in feature_ranges_orig[feature]:
--> 116                 raise ValueError("Feature", feature, "has a value outside the dataset.")
    117 
    118             if feature not in features_to_vary and permitted_range is not None:

ValueError: ('Feature', 'Invariant: Montagne', 'has a value outside the dataset.')

**Comment by noureini** [comment]
@gaugup And the code is : 

query_instances_lait = x_train[2:3]
genetic_lait = exp_genetic_lait.generate_counterfactuals(query_instances_lait, 
                                                             total_CFs=2, 
                                                             features_to_vary=['Positionnement: lait_vendu_par_sfp', 'has a value outside the dataset'],
                                                             desired_range=[1.5,2])
genetic_lait.visualize_as_dataframe(show_only_changes=True)

**Comment by noureini** [comment]
@gaugup  It is now working, I transform the dummy variable into a categorical one and declare it as such, before running my model and generating the counterfactuals. 

Thanks

**Comment by gaugup** [comment]
great. Was this due to documentation not clear? 

Could you close the issue if there is nothing actionable to do in this issue?

Regards,

**Comment by noureini** [comment]
Yes, the documentation was not clear on how to handle dummy variables, but it turns out that one has to transform them into categorical variable before generating the counterfactuals.
