### ISSUE TITLE
DiceRandom should validate the query instance

### ISSUE THREAD

**Issue by gaugup** [interpretml/DiCE#161]
If the category in some column in query_instance is not present in the training instance, then dice_genetic.py and dice_KD.py validate and throw an exception. But dice_random.py doesn't throw this exception. Specifically, the function https://github.com/interpretml/DiCE/blob/00e61efca8dbcf26cbd00f60ec8e80a6167b5782/dice_ml/explainer_interfaces/explainer_base.py#L141 needs to be called from dice_random.py as well.

**Comment by amit-sharma** [comment]
Good point. @soundarya98 can you add this to dice_random.py?

**Comment by soundarya98** [comment]
Sure! I'll add it to the tests as well

**Comment by gaugup** [comment]
Closing this issue as the attached PR is complete.
