### ISSUE TITLE
ValueError: ('Feature', ....., 'has a value outside the dataset.')

### ISSUE THREAD

**Issue by Saladino93** [interpretml/DiCE#165]
I am using DICE  0.6.

I have a classifier, with some categorial and continuous features.

When I specify the continuous features, and run Dice

`query_instances = X_train[2:3]
genetic = expl.generate_counterfactuals(query_instances, total_CFs = 1, features_to_vary = features_to_vary, permitted_range = permitted_range, desired_class = 'opposite')
genetic.visualize_as_dataframe()`

I get `ValueError: ('Feature', ...., 'has a value outside the dataset.')`

I saw there was a similar issue, here https://github.com/interpretml/DiCE/issues/122, although it was not very helpful.

The way I am 'resolving' this is by allowing all the variables to be continuous when inputting in Dice.

It works, but I get the following

`WARNING:root: MAD for feature .... is 0, so replacing it with 1.0 to avoid error.` 

Can someone please explain to me this?

Plus, if I set features_to_vary to one these categorical features, it gets stuck and it does not work...

Any thoughts?

**Comment by prateeky2806** [comment]
Hi @Saladino93 , I am not from the DICE team but maybe you can try these two things. 

1. Can you try to check the actual ranges of the all the features in the data and then see if the permitted range is a subset of that? Their code wants the permitted range to lie within the features ranges in the actual data.
2. Another thing that might be a cause is to define the variable types correctly, try specifying the continuous variable while creating the explanation classes. 

But I still feel that the it might be related to the point 1 I mentioned.

Thanks,
Prateek

**Comment by Saladino93** [comment]
Thanks @prateeky2806 . I actually get the same problem even if I define permitted range for my  generation of counterfactuals. 

I already define which variables are continuous too. Here is my code snippet:

`
d = dice_ml.Data(dataframe = data,
                 continuous_features = continuous_features,
                 outcome_name = outcome_name)

m = dice_ml.Model(model = model, backend = "sklearn", model_type = 'classifier') #(I am using an xgboost model here for classification)

expl = dice_ml.Dice(d, m, method = "genetic")

permitted_range = {}
for i, v in data[continuous_features_].items():
    permitted_range[i] = [v.min(), v.max()]

features_to_vary = 'all'

query_instances = X_train[2:3]
genetic = expl.generate_counterfactuals(query_instances, total_CFs = 10, features_to_vary = features_to_vary,
                                        permitted_range = permitted_range, desired_class = 'opposite')
genetic.visualize_as_dataframe(show_only_changes = True)

`

And then I get the error of above.

**Comment by amit-sharma** [comment]
@Saladino93 can you provide a minimum working example (with a dummy dataset) to help us debug the issue?

**Comment by Saladino93** [comment]
@amit-sharma  thanks for the reply. It turns out that the non continuous variables in the dataset have to be cast as 'category' in the pandas dataframe.

I discovered this when running DICE examples from the example notebooks. Basically the pandas dataframe when is passed as data in the dice Data, it gets automatically converted to the correct format with categorical variables as category. 

I think this part is not explained very well in the documentation, but hopefully it will be sorted out.

Thanks!

Closing now.

**Comment by emma-toh** [comment]
Hi @Saladino93 thanks for this thread! I wanted to ask what you specifically did to cast the variables as a category? I am getting a similar error: ('Feature', 'xxx', 'has a value outside the dataset.')

I have tried several things:
- identifying all the categorical features in the 'Data' that is given to the dice instance using Data[col].astype('category')
- adding a categorical_features variable to the DICE dataset 
from exp = dice_ml.Dice(d,model)
d = dice_ml.Data(dataframe=Data,
                 continuous_features=[], categorical_features=[],
                 outcome_name='')

- identifying all categorical features in the model before inputting it into the dice instance.

It's my first time using dice, thanks so much for your help!
