### ISSUE TITLE
IndexError with no categorical features (again?)

### ISSUE THREAD

**Issue by sachinsrivastava0126** [interpretml/DiCE#168]
Hello! I'm trying to use DiCE to generate CEs for a regression model (am using xgboost) and am running into an IndexError with the generate_counterfactuals code _seemingly_ due to the fact that I don't have any categorical features or because there's something wrong with the way I'm passing data. A little unsure given #2 is closed.

Here is the stack trace:
<img width="1160" alt="issue" src="https://user-images.githubusercontent.com/15526466/123566249-35542680-d78d-11eb-9d89-245a6afbed37.png">

And the offending code (penultimate line):
````
outcome = "Target"
dice_df_copy = dice_df.copy() 
cont_features = dice_df_copy.drop("Target",axis=1).columns.tolist() 
dice_data = dice_ml.Data(dataframe=dice_df, continuous_features=cont_features, outcome_name=outcome) dice_model = dice_ml.Model(model=xgb_model, backend="sklearn",model_type="regressor") 

exp_genetic = Dice(dice_data, dice_model, method="genetic") 
gen_CE = exp_genetic.generate_counterfactuals(query_instances=dice_df[0:1], total_CFs=1, desired_range=[19,20], stopping_threshold=0.00, posthoc_sparsity_algorithm="binary", verbose=True) 
gen_CE.visualize_as_dataframe(show_only_changes=True)
````

I've tried changing the type of the data I pass as the query_instances param from a dataframe to a list of 1 dict object (a singular dict object threw an exception prompting me to alter that datatype) and the result is that the code runs but then is stuck running for hours. All I get is: "Initializing initial parameters to the genetic algorithm..."

Any guidance would be appreciated! Thanks

**Comment by gaugup** [comment]
@sachinsrivastava0126, which version of dice-ml library are you using? The referenced issue was reported long back. Could you try with the latest dice-ml release 0.6.1?

**Comment by sachinsrivastava0126** [comment]
Yes using 0.6.1

**Comment by gaugup** [comment]
Would you be able to share a sample notebook and dataset? I want to see if you are setting up the dice-ml explainer correctly.

**Comment by sachinsrivastava0126** [comment]
The code/dataset isn't entirely mine so I am trying to get permission. I've been following this notebook for the setup: https://github.com/interpretml/DiCE/blob/master/docs/source/notebooks/DiCE_multiclass_classification_and_regression.ipynb

In the meantime, here is the code where I instantiate the DiCE instance.

It's a bit messy but here's some info that might be useful
- dice_df is a copy of X_train
- I insert the target variable values into the dice_df. This is essentially recreating the original dataset except that all values are now numeric
- I had some typing errors so I do some casting from pandas Series to ints for categorical features

Setup:
- I get all the columns of dice_df except for the target variable to be the continuous features since everything is numerically encoded at this point
- I then pass in dice_df which is again just a copy of X_train, continuous features, and the target as the outcome variable into the dice_ml.Data instance
- In the dice_ml.Model instance I've tried passing in the xgboost instance itself (of type <class 'xgboost.sklearn.XGBRegressor'>) as well as a Pipeline instance as shown in the tutorial notebook I referenced above. Both approaches still yield the error from my original post



```
dice_df = X_train.copy()
dice_df.insert(1,"Target",y_train)

for feature in features_nom:
  if feature!="Misc":
    dice_df[feature] = dice_df[feature].astype(int)
  
for feature in ordered_levels.keys():
  if feature!='QC':
    dice_df[feature] = dice_df[feature].astype(int)
  

## Attempted setup code ##
outcome = "Target"
cont_features = dice_df.drop("Target",axis=1).columns.tolist() 
dice_data = dice_ml.Data(dataframe=dice_df, continuous_features=cont_features, outcome_name=outcome) dice_model = dice_ml.Model(model=xgb_model, backend="sklearn",model_type="regressor") 

exp_genetic = Dice(dice_data, dice_model, method="genetic") 
gen_CE = exp_genetic.generate_counterfactuals(query_instances=dice_df[0:1], total_CFs=1, desired_range=[19,20], stopping_threshold=0.00, posthoc_sparsity_algorithm="binary", verbose=True) 
gen_CE.visualize_as_dataframe(show_only_changes=True)

```

**Comment by sachinsrivastava0126** [comment]
Here is the notebook: https://colab.research.google.com/drive/1zrnTCmAXJpcTiWGnbPYjtdepWApBt9zY?usp=sharing

Most of the model code can be ignored and comes from here: https://www.kaggle.com/ryanholbrook/feature-engineering-for-house-prices

Dataset: https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data

**Comment by gaugup** [comment]
@sachinsrivastava0126, I will take a look at this today. Thanks for the pointers.

Regards,

**Comment by sachinsrivastava0126** [comment]
@gaugup 

Update here. I had the wrong link previously. Sorry for any mix up

Here is the notebook: https://colab.research.google.com/drive/1zrnTCmAXJpcTiWGnbPYjtdepWApBt9zY?usp=sharing

Most of the model code can be ignored and comes from here: https://www.kaggle.com/ryanholbrook/feature-engineering-for-house-prices

Dataset: https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data

**Comment by soundarya98** [comment]
Dear @sachinsrivastava0126, 
could you try dropping the outcome column and check if the error persists? I tried running the notebook, and it seems that this error gets fixed (and another one pops up) after the change. 

`dice_df = dice_df.drop('SalePrice', axis=1)`

**Comment by sachinsrivastava0126** [comment]
The error that popped up was because I accidentally deleted the line where the model is fit. Fixed.

I've tried dropping SalePrice from dice_df as well as passing in different formats to the query_instances parameter (dataframe, dict, list of 1 dict) and previously generate_counterfactuals seemingly got stuck at "Initializing initial parameters to the genetic algorithm..." for over 2 hours. This doesn't seem like expected behavior because I only have around 80 features but please let me know if I'm mistaken. I'm running with no restrictions on features_to_vary or permitted_ranges and am trying to generate 1 counterfactual

**Comment by Saladino93** [comment]
I am also obtaining the same problem, when using only continuous features...

`IndexError: list index out of range`

**Comment by soundarya98** [comment]
Dear @sachinsrivastava0126, 

The code is stuck in initialising parameters for the genetic algorithm because the model isn't able to find cfs in the desired_range that you have specified. I think this is because the model is trained poorly. 

For example:
![image](https://user-images.githubusercontent.com/37398880/124287770-09aab500-db6e-11eb-9aa6-af4d6475976b.png)

Here, as you can see, the values of the SalePrice in the training data are of a much higher range than what the model is predicting. DiCE's genetic algorithm uses the predict function of the trained model, so if the model is outputting values in the range 10-20, it would never reach the high desired_range of (190000,200000). Thus, my suggestion would be to either re-train the model, or to change the desired_range.

**Comment by gaugup** [comment]
@sachinsrivastava0126, could you try with the findings from @soundarya98's response above? Could you look at your model training phase?

Regards,

**Comment by sachinsrivastava0126** [comment]
@soundarya98 @gaugup Sorry for the late reply. Thank you for noticing this oversight. The model is returning log(SalePrice) so I've changed the desired_range to account for this. However, I'm now once again running into an IndexError issue similar to the one in my original post. I'm using 1 query instance (X_train[279:280]) and requesting 1 counterfactual with no restrictions on which features to vary or their permitted ranges. The code is accessible in the notebook shared above but also pasted below. I've also included the stack trace for this IndexError


```
dice_df = X_train.copy()
dice_df.insert(1,"SalePrice",y_train)

for feature in features_nom:
  if feature!="MiscFeature":
    dice_df[feature] = dice_df[feature].astype(int)
  
for feature in ordered_levels.keys():
  if feature!='PoolQC':
    dice_df[feature] = dice_df[feature].astype(int)



outcome = 'SalePrice'
cont_features = dice_df.drop("SalePrice",axis=1).columns.tolist()

### Line below commented out because errors 
### "UserConfigValidationException: outcome_name SalePrice not found in MSSubClass,MSZoning,LotFrontage,etc" 
# dice_df = dice_df.drop('SalePrice', axis=1) 


dice_data = dice_ml.Data(dataframe=dice_df, continuous_features=cont_features, outcome_name=outcome)
dice_model = dice_ml.Model(model=xgb_model, backend="sklearn", model_type="regressor")

exp_genetic = Dice(dice_data,dice_model,method="genetic")
gen_CE = exp_genetic.generate_counterfactuals(query_instances=X_train[279:280],
                                    total_CFs=1,
                                    desired_range=[12.156,12.3],
                                    stopping_threshold=0.00,
                                    posthoc_sparsity_algorithm="binary",
                                    verbose=True)
gen_CE.visualize_as_dataframe(show_only_changes=True)
```





Stack trace:
<img width="1246" alt="Screen Shot 2021-07-02 at 6 00 19 PM" src="https://user-images.githubusercontent.com/15526466/124332775-4c659080-db60-11eb-8128-f038a193758d.png">

**Comment by gaugup** [comment]
@sachinsrivastava0126, you should include the SalesPrice in the dice_df and SalesPrices shouldn't be present in query_instances passed into generate_counterfactuals(). Can you please make sure that? Not sure what is X_train.

Regards,

**Comment by sachinsrivastava0126** [comment]
@gaugup  SalePrice is included in dice_df and not in the query_instance passed into generate_counterfactuals. X_train[279:280] is just an input example from the training set that I'm trying to generate a counterfactual for. Here is some output to confirm the details you mentioned

<img width="420" alt="Screen Shot 2021-07-02 at 11 14 41 PM" src="https://user-images.githubusercontent.com/15526466/124341577-4cc75100-db8b-11eb-9558-ad720685effa.png">

**Comment by soundarya98** [comment]
Dear @sachinsrivastava0126, thank you very much for bringing this issue to our notice. We have noticed a couple of bugs and will raise a PR shortly to resolve the issue.

**Comment by sachinsrivastava0126** [comment]
@soundarya98 @gaugup No problem. Thanks much for your assistance. When can we expect the changes to be merged?

**Comment by sachinsrivastava0126** [comment]
@soundarya98 @gaugup  No problem. Thank you so much for your help! Closing
