### ISSUE TITLE
How can I save the CounterfactualExamples to a csv file？

### ISSUE THREAD

**Issue by djlwzw** [interpretml/DiCE#174]
Hi, I want to save the CounterfactualExamples to a csv file. But I don't know how to do it?
Because I have many features in data, I can't see all the features in the dataframe.
So I need a help, thank you very much.

Such as this,
Diverse Counterfactual set (new outcome: 0.0)
  1_day 1_log 1_event_type 1_problem  ... 5_server 5_browser 5_module drop
0   7.0     -          1.0      34.0  ...    198.0         -        -  0.0
1   5.0  15.0          1.0      34.0  ...      0.0         -        -  0.0

**Comment by amit-sharma** [comment]
@djlwzw the counterfactual set is actually a pandas dataframe. You can access the pandas dataframe as `e1.cf_examples_list[0].final_cfs_df` and then use [`df.to_csv()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html) function from pandas to store as a csv. For details see the answer in #119 

```
e1 = exp.generate_counterfactuals(x_train[0:1], total_CFs=2, desired_class="opposite")
e1.visualize_as_dataframe(show_only_changes=True)
e1.cf_examples_list[0].final_cfs_df
```

**Comment by djlwzw** [comment]
Thank you very much for your help, my problem has been solved, thank you again

**Comment by ramaswami1gomathy** [comment]
Hi, can anyone help me in saving the counterfactual as a CSV file? I tried using the above-mentioned method (df.to_csv())but not working.
