### ISSUE TITLE
Get raw counterfactual data as dataframe

### ISSUE THREAD

**Issue by MLcase** [interpretml/DiCE#191]
Hi,

in the getting started notebook, the counterfactuals are obtained by creating a `CounterfactualExplanations` object `e1` and then calling `visualize_as_dataframe()` on it. However, instead of visualizing the dataframe, is it possible to get access to the dataframe as a pandas object?

Thanks :)

Martin

**Comment by amit-sharma** [comment]
See this issue: #174. Does it solve your problem?

**Comment by MLcase** [comment]
That's exactly what I was looking for, thank you very much :)

I will close this issue now.
