### ISSUE TITLE
Can local importance be greater than one?

### ISSUE THREAD

**Issue by Saladino93** [interpretml/DiCE#195]
Not sure if I misunderstood it non correctly, but I thought local importance was the fraction of changes for a particular feature when generating N counterfactuals for a particular example. Being a fraction, by definition it should be at most 1.

But, I ran an example with some dataset, and I got this:

<img width="520" alt="Screenshot 2021-07-30 at 10 26 35" src="https://user-images.githubusercontent.com/23438226/127632508-fd1921f3-762b-4e9b-8059-bad7d42b63f2.png">

This does not make sense to me, if I understood things right.

Also I find it strange when several features have the same value of local importance (e.g. they are all one, or all the same value). It is like the calculation of local importance loses a bit of sense..... So maybe in these cases one should also use the gobal one, boh, I am not sure about the correct reasoning here.

p.s.
I can not show the variables, and the dataset.

**Comment by gaugup** [comment]
@Saladino93, from the logic it does not looks like it local importance should not be greater than 1.0. One possiblitiy is some feature being regarded both as categorical and continous. Can you check your configuration?

Regards,

**Comment by Saladino93** [comment]
Sorry @gaugup  what do you mean by "One possiblitiy is some feature being regarded both as categorical and continous"? 

I set all the continuous variables with the dedicated key word. I thought it was a bug as it should not give at most one.... Will check!

**Comment by gaugup** [comment]
@Saladino93, I see a potential bug in calculation of local importance. Could you maybe share a notebook where you see this issue?

Regards,

**Comment by gaugup** [comment]
@Saladino93, I was able to find a bug in the computation of the feature importances. The PR to fix this is at https://github.com/interpretml/DiCE/pull/199/files. Could you maybe try with the changes in explainer_base.py in this PR to see if that fixes your local feature importnace problem here?

Regards,

**Comment by Saladino93** [comment]
@gaugup  fantastic, thanks a lot mate!

Here is the result 
<img width="486" alt="Screenshot 2021-08-04 at 13 11 40" src="https://user-images.githubusercontent.com/23438226/128178588-dc26c3cd-1a4c-4153-b6b7-5650f71a3e0a.png">

Now my only problem is that there are too many features at one hahaa. Probably I have to look into how the changes are made. Also I have to understand this substitution of MAD from 0 to 1.

Thanks again @gaugup , have a nice day!!
