### ISSUE TITLE
Converting the counterfactuals as a DataFrame

### ISSUE THREAD

**Issue by jtonglet** [interpretml/DiCE#201]
Thanks for the great tool!
It is currently possible to visualize the counterfactuals as a DataFrame.

Is it also possible to actually store the counterfactuals in a Pandas DataFrame object for further manipulations with Seaborn, matplotlib, ... ?

**Comment by gaugup** [comment]
@jtonglet, could you maybe look at the discussion in issue https://github.com/interpretml/DiCE/issues/174 to see if it helps answet your question?

Regards,
