### ISSUE TITLE
Running Dataset mentioned in FAT 20 conference paper

### ISSUE THREAD

**Issue by learnXAI** [interpretml/DiCE#209]
Hi,

I am trying to Use DICE to generate CFs on other datasets (Lending Club, German-credit, and Compas) mentioned in the DICE paper of 'FAT 20' but unlike Adult-income dataset, I do not see any tutorial on GItHub about how to run the others. Can you please berief idea on what I need to do to be able to run models trained on other datasets.

I will really appreciate your help!
looking forward to your reply.

**Comment by amit-sharma** [comment]
You can look at the answer to this issue #170 That has a link to the relevant code.

**Comment by learnXAI** [comment]
Thank you, Amit. 
Appreciate your help!
