### ISSUE TITLE
Generating opposite class does not work as expected

### ISSUE THREAD

**Issue by Saladino93** [interpretml/DiCE#215]
Hi all,

here is the problem: given a binary classifier, when generating counterfactuals with desired_class='opposite' class as desired, if the original outcome is 0, then the counterfactual has 1 as new outcome. But, if the original outcome is 1, then the counterfactual is still 1 as new outcome, giving me different inputs that lead to 1. 

I have to manually set desired_class to 0 for the cases of 1.

I discovered this while doing for an example of mine, although I can reproduce this also with the
DiCE_model_agnostic_CFs.ipynb example.

Here is a snippet:

`dice_exp_genetic = exp_genetic.generate_counterfactuals(query_instances, total_CFs=4, desired_class='opposite', verbose=True)`

Result

![image](https://user-images.githubusercontent.com/23438226/130958557-dd603dd5-f003-4819-bdfa-868da4668965.png)

**Comment by ninaspreitzer** [comment]
I am having a similar issue, but also when the outcome is 0 and should be changed to 1 
was there any solution found already? 
(These are basic settings, didn't change anything from the code)
<img width="902" alt="Bildschirmfoto 2022-05-09 um 18 05 54" src="https://user-images.githubusercontent.com/57034840/167466091-5c6d1e20-4197-40fc-a468-5fff2c47cd5a.png">

**Comment by lange-martin** [comment]
> was there any solution found already?

I don't believe so. The workaround I am currently using is to input the `desired_class` manually.
