### ISSUE TITLE
.to_json() throwing error

### ISSUE THREAD

**Issue by javirandor** [interpretml/DiCE#247]
I encountered some problems when using the method `.to_json()` in counterfactuals. I don't really know what is making it crash in certain scenarios. You can reproduce it by using your public Notebook for classification: https://github.com/interpretml/DiCE/blob/master/docs/source/notebooks/DiCE_multiclass_classification_and_regression.ipynb

If you try to generate a JSON dump of the first set of counterfactuals like this `genetic_iris.to_json()`, the following error raises `TypeError: Object of type 'float32' is not JSON serializable`

**Comment by gaugup** [comment]
@javirandor what version of dice-ml are you seeing this issue with?

**Comment by gaugup** [comment]
@javirandor, I was able to repro the issue using the referred notebook. I have created a PR https://github.com/interpretml/DiCE/pull/248 to fix this issue. The fix should be able in the upcoming dice-ml release.

Regards,
