### ISSUE TITLE
Error line 262 dice_KD.py

### ISSUE THREAD

**Issue by giandos200** [interpretml/DiCE#254]
Hi, I am using Dice to find different counterfactuals for each instance. However a simple error appears while running my code. In the file dice_KD.py when the tool finds fewer counterfactuals than those requested in the print at line 262 
 
               print('Only %d (required %d) ' % (total_cfs_found, self.total_CFs),
 
the attribute self.total_CFs is never defined before. Certainly solvable in a jiffy, I hope that was helpful.
Cordially,
Giandomenico Cornacchia

**Comment by gaugup** [comment]
@giandos200 thanks for pointing out the issue. I have created PR https://github.com/interpretml/DiCE/pull/255 to address this.

Regards,

**Comment by giandos200** [comment]
Hi @gaugup! I'm using dice in order to search for more CF for a single instance (>= one hundreds)and i've changed something in the code in order to speed up the KDTree init in the GA. Can i partecipate in the PR #255 or should i open a new PR to push the suggested improvements?

**Comment by gaugup** [comment]
@giandos200 feel free to aend another PR to for computation speed up. This will be a great enhancement to add. We will help with the reviews.

Regarda,
