### ISSUE TITLE
Replace load_boston with alternate regression dataset

### ISSUE THREAD

**Issue by gaugup** [interpretml/DiCE#265]
As noted in https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_boston.html the Boston housing dataset is being deprecated due to a significant ethical concern:

Warning: The Boston housing prices dataset has an ethical problem: as investigated in [1], the authors of this dataset engineered a non-invertible variable “B” assuming that racial self-segregation had a positive impact on house prices [2]. Furthermore the goal of the research that led to the creation of this dataset was to study the impact of air quality but it did not give adequate demonstration of the validity of this assumption.

The scikit-learn maintainers therefore strongly discourage the use of this dataset unless the purpose of the code is to study and educate about ethical issues in data science and machine learning.

Sklearn suggests that either the California housing dataset or the Ames housing dataset are reasonable alternative datasets [https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_boston.html]. We should change references in DiCE accordingly.

**Comment by danielsaggau** [comment]
I saw the same issue and tried to replicate the example for the California housing dataset. Attached the link to the notebook I am using. It is still a WIP though: https://github.com/danielsaggau/DICE/blob/master/Cali_DiCE.ipynb
