### ISSUE TITLE
panda.append()

### ISSUE THREAD

**Issue by giandos200** [interpretml/DiCE#279]
Method deprecated, please substitute row 124 of dice_random.py with:
`cfs_df = pd.concat([cfs_df,rows_to_add])`
and row 562 of dice_genetic.py with:
`ret_df = pd.concat([ret_df,df])`

**Comment by gaugup** [comment]
Thanks @giandos200  for the suggestion. We have a created a PR at https://github.com/interpretml/DiCE/pull/280 to make this change.

Regards,
