### ISSUE TITLE
Accessing counterfactual dataframe

### ISSUE THREAD

**Issue by PaoloFantine** [interpretml/DiCE#283]
Is there any way to return the data frame (or a dict) with the counterfactuals? Currently, I can only visualize the counterfactuals as a data frame, but accessing it would allow, for example, to produce plots and so on without too much manual effort. I think it would be a rather simple addition?

**Comment by amit-sharma** [comment]
Refer to #174 Hope that solves your issue.

**Comment by PaoloFantine** [comment]
Solves it. Thank you very much!

**Comment by gaugup** [comment]
@PaoloFantine closing this issue as your query has been answered. Please re-open if you think you need help with accessing the counterfactuals dataframe.

Regards,
