### ISSUE TITLE
Feature ranges

### ISSUE THREAD

**Issue by PaoloFantine** [interpretml/DiCE#284]
I am using the drug consumption dataset for a multiclass classification and trying to enforce some permitted ranges like:
```
d = dice_ml.Data(dataframe = eval_data, 
                 continuous_features = continuous_features, 
                 outcome_name = self.target_name)
        
 m = dice_ml.Model(model = model, backend = backend)
 
 exp = dice_ml.Dice(d, m, method="random")
        
 e1 = exp.generate_counterfactuals(instance = 0,
                   continuous_features = ['nscore', 'escore', 'oscore', 'ascore', 'cscore', 'impulsive', 'ss'],
                   model = model, 
                   backend = "sklearn", 
                   total_CFs = 5,
                   desired_class = 2,
                   features_to_vary = ['nscore', 'escore', 'oscore', 'ascore', 'cscore', 'impulsive', 'ss'],
                   permitted_range = {'oscore':[-1.0, 2.0], 'ascore':[0.0, 0.5], 'cscore':[0.0, 1.0], 'ss':[-2.0, 1.0 ]})
```

however, I get counterfactuals with values well outside those ranges. I wonder whether this is a bug or, in case there are no available counterfactuals within those ranges, they are somehow overidden?

**Comment by gaugup** [comment]
@PaoloFantine there are no parameters like 'continuous_features', 'instance', 'model', 'backend' in the `generate_counterfactuals` method. Could you may be use the sample notebooks from https://github.com/interpretml/DiCE/blob/master/docs/source/notebooks/DiCE_getting_started.ipynb to correct the above code?

**Comment by gaugup** [comment]
We should be respecting the range. If you could share a sample notebook and dataset, it will be possible for us to dig into this issue.

Regards,

**Comment by tonyabracadabra** [comment]
> We should be respecting the range. If you could share a sample notebook and dataset, it will be possible for us to dig into this issue.
> 
> Regards,

apart from the ranges for the continuous variables, how can I set the range for categorical variables? for example I have a categorical variable that contains four categories (A, B, C, D) and I only want the counterfactuals to vary to `A, B, C` excluding `D`

**Comment by gaugup** [comment]
@tonyabracadabra, You can do something like this below:-

```
            exp.generate_counterfactuals(
                query_instances=sample_custom_query_1,
                total_CFs=10,
                desired_class=desired_class,
                desired_range=None,
                permitted_range={'Categorical': ['A', 'B', 'C']},
                features_to_vary='all')
```

That should be a signal to dice to use only categories 'A', 'B' and 'C' to generate counterfactuals.

Hope this helps.

P.S. Since this question is not related to the original question, we will really appreciate if you opened a new issue for these queries.
