### ISSUE TITLE
Counterfactual for subpopulation 

### ISSUE THREAD

**Issue by tonyabracadabra** [interpretml/DiCE#302]
Can DiCE be extended for calculating the counterfactuals for a subpopulation based on certain conditions?

**Comment by amit-sharma** [comment]
yes, you can provide a set of rows from a dataframe to the `generate_counterfactuals` method. One way is to filter the dataframe based on given conditions and then supply the filtered dataframe to `generate_counterfactuals`. 

However, you will still get counterfactuals per row. Is that the goal?

**Comment by tonyabracadabra** [comment]
> yes, you can provide a set of rows from a dataframe to the `generate_counterfactuals` method. One way is to filter the dataframe based on given conditions and then supply the filtered dataframe to `generate_counterfactuals`.
> 
> However, you will still get counterfactuals per row. Is that the goal?

I was thinking if there is a more efficient way of doing this, I was reading this https://arxiv.org/pdf/2103.11972.pdf and wonder if there is anything similar can help me achieving the contextual algorithm recourse

**Comment by amit-sharma** [comment]
The method from the arxiv paper is not currently implemented. Will be a great contribution if you/someone is up for it.
