### ISSUE TITLE
Generating CF examples for the multi-class classification case using the GD-based method

### ISSUE THREAD

**Issue by ah-ansari** [interpretml/DiCE#305]
Hi,

I was wondering if the current implementation of the GD-based method (I mean the loss-based method described in your paper, [Mothilal et al. (2020)](https://arxiv.org/abs/1905.07697)) can handle the multi-class classification case? 

I see in [dice_tensorflow2.py](https://github.com/interpretml/DiCE/blob/master/dice_ml/explainer_interfaces/dice_tensorflow2.py), that the "desired_class" parameter can only be 0 or 1. 

Many thanks that you take the time to answer the questions.

**Comment by amit-sharma** [comment]
We are working on supporting multi-class, but the current version on tensorflow supports only binary at the moment.

**Comment by ah-ansari** [comment]
Thanks for your response.

For a submission, I need to apply your method to a multi-class problem, for which I will cite your work.
Unfortunately, my time is limited, and I would appreciate it if you describe how I modify the code so it can be applied for multi-class case (if the change is simple).
I think if I modify the "predict_fn" function in [dice_tensorflow2.py](https://github.com/interpretml/DiCE/blob/master/dice_ml/explainer_interfaces/dice_tensorflow2.py), then the method would work without any more changes. Am I correct?

**Comment by amit-sharma** [comment]
That's correct. you will need to change the predict_fn. But you may find that the rest of the code expects a single-dimensional value as output of classifier---so you may need to change those parts to do "max of the output scores" rather than "is output score more than 0.5/threshold".

Hope this helps. Happy to answer any questions as you go through the code, and would love if you can raise a PR with these changes after your submission.

**Comment by ah-ansari** [comment]
Many thanks for your help.
Sure, I will raise a PR after I applied the changes.

**Comment by jainspoornima** [comment]
Could you kindly confirm if multi-class classification is supported for PyTorch/Tensorflow backend now?

**Comment by amit-sharma** [comment]
yes, it is supported now in the latest release.

**Comment by jainspoornima** [comment]
Thanks a lot for confirming sir.

I am working on a multi-class classification problem with 50 classes, and I have label-encoded the targets from 0-49. But I am getting the following error in the below line while generating counterfactuals - 

dice_exp = exp.generate_counterfactuals(X_test[1:2], total_CFs=1, desired_class=10)

```
OverflowError                             Traceback (most recent call last)
[<ipython-input-101-cf732e86583b>](https://localhost:8080/#) in <cell line: 22>()
     20 print(X_test[1:2].shape)
     21 # generate counterfactuals
---> 22 dice_exp = exp.generate_counterfactuals(X_test[1:2], total_CFs=1, desired_class=10)
     23 # visualize the result, highlight only the changes
     24 dice_exp.visualize_as_dataframe(show_only_changes=True)

1 frames
[/usr/local/lib/python3.10/dist-packages/dice_ml/explainer_interfaces/dice_tensorflow2.py](https://localhost:8080/#) in generate_counterfactuals(self, query_instance, total_CFs, desired_class, proximity_weight, diversity_weight, categorical_penalty, algorithm, features_to_vary, permitted_range, yloss_type, diversity_loss_type, feature_weights, optimizer, learning_rate, min_iter, max_iter, project_iter, loss_diff_thres, loss_converge_maxiter, verbose, init_near_query_instance, tie_random, stopping_threshold, posthoc_sparsity_param, posthoc_sparsity_algorithm, limit_steps_ls)
    124 
    125         # if([total_CFs, algorithm, features_to_vary] != self.cf_init_weights):
--> 126         self.do_cf_initializations(total_CFs, algorithm, features_to_vary)
    127         if [yloss_type, diversity_loss_type, feature_weights] != self.loss_weights:
    128             self.do_loss_initializations(yloss_type, diversity_loss_type, feature_weights)

[/usr/local/lib/python3.10/dist-packages/dice_ml/explainer_interfaces/dice_tensorflow2.py](https://localhost:8080/#) in do_cf_initializations(self, total_CFs, algorithm, features_to_vary)
    182                 one_init = [[]]
    183                 for jx in range(self.minx.shape[1]):
--> 184                     one_init[0].append(np.random.uniform(self.minx[0][jx], self.maxx[0][jx]))
    185                 self.cfs.append(tf.Variable(one_init, dtype=tf.float32))
    186 

mtrand.pyx in numpy.random.mtrand.RandomState.uniform()

OverflowError: Range exceeds valid bounds
```

Just sharing the code snippet here too - https://github.com/jainspoornima/Counterfactuals_AlgorithmicRecourse/blob/main/counterfactual_multiclass_TF.py

Any suggestion on the same would be very helpful. 
Thank you.
