### ISSUE TITLE
wrong new_outcome for method 'genetic' 'kdtree'

### ISSUE THREAD

**Issue by WeituoDAI** [interpretml/DiCE#314]
Hi, I have tried to use three methods to get CounterfactualExamples in Jupyter notebook.  But I find the **_new_outcome_** is wrong sometimes when _**desired_class=="opposite".**_
And I check your code, I find that for "genetic" and "kdtree" methods, you compute the **_desired_class_** in  **_generate_counterfactuals()** (like in dice.KD.py ), but I think you should compute it for every instance (like the method of 'random'), that is right?

**Comment by amit-sharma** [comment]
This has been fixed with v0.9. Let us know if you still face this issue.

**Comment by WeituoDAI** [comment]
It works well now. Thank you. 


De: "Amit Sharma" ***@***.***> 
À: "interpretml/DiCE" ***@***.***> 
Cc: "WeituoDAI" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Jeudi 20 Octobre 2022 06:42:23 
Objet: Re: [interpretml/DiCE] wrong new_outcome for method 'genetic' 'kdtree' (Issue #314) 





This has been fixed with v0.9. Let us know if you still face this issue.
