### ISSUE TITLE
Identifying categorical values in private data method

### ISSUE THREAD

**Issue by LornaAS93** [interpretml/DiCE#317]
I'm trying to use the method for identifying counterfactuals without access to the training data. I have defined my feature dictionary containing the min/max numerical values and expected categorical values. However, I'm getting errors with numerical columns where the values are floats instead of integers. 

I can see in the private_data_interface.py code that columns are classed as categorical columns if they are not integers, but it makes sense to also include float values in the accepted numerical type?

```
for feature in features_dict:
            if type(features_dict[feature][0]) is int:  # continuous feature
                self.continuous_feature_names.append(feature)
                self.permitted_range[feature] = features_dict[feature]
            else:
                self.categorical_feature_names.append(feature)
                self.categorical_levels[feature] = features_dict[feature]
```

**Comment by amit-sharma** [comment]
Thanks for suggesting this. Fixed in #330
