### ISSUE TITLE
Error ‘unexpected keyword argument 'output_type'’ when trying  to reproduce the example notebook with private data

### ISSUE THREAD

**Issue by BlagaBaycheva** [interpretml/DiCE#318]
Hi, when trying to generate counterfactuals with private data using the toy adult dataset and reproducing the provided notebook example I’m getting the following error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp\2\ipykernel_3336\1826134958.py in <module>
----> 1 exp = dice_ml.Dice(d, m, method="random")

C:\Anaconda\envs\R011-Counterfactuals\lib\site-packages\dice_ml\dice.py in __init__(self, data_interface, model_interface, method, **kwargs)
     19         :param method: Name of the method to use for generating counterfactuals
     20         """
---> 21         self.decide_implementation_type(data_interface, model_interface, method, **kwargs)
     22 
     23     def decide_implementation_type(self, data_interface, model_interface, method, **kwargs):

C:\Anaconda\envs\R011-Counterfactuals\lib\site-packages\dice_ml\dice.py in decide_implementation_type(self, data_interface, model_interface, method, **kwargs)
     29                     ' since kdtree explainer needs access to entire training data')
     30         self.__class__ = decide(model_interface, method)
---> 31         self.__init__(data_interface, model_interface, **kwargs)
     32 
     33     def _generate_counterfactuals(self, query_instance, total_CFs,

C:\Anaconda\envs\R011-Counterfactuals\lib\site-packages\dice_ml\explainer_interfaces\dice_random.py in __init__(self, data_interface, model_interface)
     31         self.model.transformer.initialize_transform_func()
     32 
---> 33         self.precisions = self.data_interface.get_decimal_precisions(output_type="dict")
     34         if self.data_interface.outcome_name in self.precisions:
     35             self.outcome_precision = [self.precisions[self.data_interface.outcome_name]]

TypeError: get_decimal_precisions() got an unexpected keyword argument 'output_type'

**Comment by amit-sharma** [comment]
@BlagaBaycheva the notebook has been updated now. Can you try the new [notebook](https://github.com/interpretml/DiCE/blob/main/docs/source/notebooks/DiCE_with_private_data.ipynb) using the main branch code (i.e., install the library from github--clone and then `pip install -e  .` from the root directory)

**Comment by amit-sharma** [comment]
This has been fixed in the new version, v0.9.
