### ISSUE TITLE
`visualize_as_dataframe` heading mistakenly produces "new outcome: 1" regardless of `desired_class` in `generate_counterfactuals`

### ISSUE THREAD

**Issue by moyaghini** [interpretml/DiCE#33]
```
import dice_ml
from dice_ml.utils import helpers # helper functions

# Dataset for training an ML model
d = dice_ml.Data(dataframe=helpers.load_adult_income_dataset(),
                 continuous_features=['age', 'hours_per_week'],
                 outcome_name='income')
# Pre-trained ML model
m = dice_ml.Model(model_path=dice_ml.utils.helpers.get_adult_income_modelpath(), backend="TF2")

# DiCE explanation instance
exp = dice_ml.Dice(d,m)

query_instance = {'age':22,
    'workclass':'Private',
    'education':'HS-grad',
    'marital_status':'Single',
    'occupation':'Service',
    'race': 'White',
    'gender':'Female',
    'hours_per_week': 45}

# Generate counterfactual examples
dice_exp = exp.generate_counterfactuals(query_instance, total_CFs=4, desired_class=0)
# Visualize counterfactual explanation
dice_exp.visualize_as_dataframe()
```

Produces:

<img width="685" alt="image" src="https://user-images.githubusercontent.com/61885784/90339185-6bb90500-e004-11ea-9862-cd0db6f3f460.png">

**Comment by raam93** [comment]
Ah well, it's because you have provided `desired_class=0` in the `generate_counterfactuals()` method. The default value is `opposite`, so provide `desired_class="opposite"` and DiCE will automatically infer the counterfactual class from the query instance's output.

**Comment by amit-sharma** [comment]
@moyaghini for binary class labels, you are right. But the parameter becomes important for multi-class classification, where "opposite" may not make sense, but the user can specify the target class for which CFs should be generated (among the k-1 classes left).

**Comment by raam93** [comment]
Ok, I see the issue - it is a printing error @moyaghini. Thanks for bringing that up! If you see the predicted values of the outcome feature "income", it is below 0.5 only. You can always generate CFs for any outcome class. However, while displaying (the line above CFs table), we have set the wrong default where it sets the opposite class as the new outcome. Have updated the library, please check in a while and let us know if the same issue persists. Thank you!
