### ISSUE TITLE
Incorrect Target values when using Tensor Flow v2 Model

### ISSUE THREAD

**Issue by LiNaNiNa** [interpretml/DiCE#333]
Hello,
When executing the code code (applying DICE on half_moons dataset with Tensor Flow 2 model), the 'target' column of the counterfactuals (in HERE (A) and HERE (B) below) is different than the result predicted by Tensor Flow model for the examples [results shown below].  And thus, the counterfactuals do not all belong to the opposite class, even if it is shown that they are. 
Is this an issue or did I misconfigure the DICE method?
Thank you for your hard work!
```
import dice_ml
from sklearn import datasets
import numpy as np
import pandas as pd

#create dataset
X1, Y1 = datasets.make_moons(n_samples=1000, noise=0.2)

s = {'x1': X1[:,0], 'x2': X1[:,1], 'target': Y1}
df = pd.DataFrame(data=s)

d = dice_ml.Data(dataframe=df,
                 continuous_features=['x1', 'x2'],
                 outcome_name='target')

import tensorflow as tf
import keras
X_train = X1
y_train = Y1
ann_model = keras.Sequential()
ann_model.add(keras.layers.Dense(20, input_shape=(X_train.shape[1],), kernel_regularizer=keras.regularizers.l1(0.001), activation=tf.nn.relu))
ann_model.add(keras.layers.Dense(1, activation=tf.nn.sigmoid))
ann_model.compile(loss='binary_crossentropy', optimizer=tf.keras.optimizers.Adam(0.01), metrics=['accuracy'])
ann_model.fit(X_train, y_train, validation_split=0.20, epochs=100, verbose=True)

#Generate the DiCE model for explanation
m = dice_ml.Model(model=ann_model, backend='TF2')

explainer = dice_ml.Dice(d,m)
query_instance = {'x1':0, 'x2':0}

#verification:
x_test = np.array([[0,0]])
ann_model.predict(x_test) #0.99

counterfactuals = explainer.generate_counterfactuals(
    query_instance,
    total_CFs = 4,
    desired_class=0,
    proximity_weight=0.5,
    diversity_weight=1.0,
    features_to_vary="all",
    permitted_range=None,
    posthoc_sparsity_param=0.1)

counterfactuals.visualize_as_dataframe() #HERE (A)

print(counterfactuals.cf_examples_list[0].final_cfs_df) #HERE (B)
```
Results:
The output of dice:
![image](https://user-images.githubusercontent.com/48122614/196043083-ca68d593-2eb1-4374-b152-a44e5eac1608.png)
The prediction of the TF model (same order of the points):
![image](https://user-images.githubusercontent.com/48122614/196043114-5c602615-2361-4c2c-aa60-401c3d155610.png)

**Comment by amit-sharma** [comment]
hi @LiNaNiNa This issue was fixed in the latest main branch. Can you try cloning the latest main branch from github and try this code again? (clone the repo and then do `pip install -e  .` from the root folder of the repo).

**Comment by LiNaNiNa** [comment]
Hello, 
Thank you for your fast answer, @amit-sharma .

Yes, the latest version works well!
The only change I did (for future reference), is changing the type of query_instance argument for explainer.generate_counterfactuals method, from a dictionary to a dataframe. But, right now, it can work on multiple instances in one run! Thank you for the new feature.

Keep up the hard work!
