### ISSUE TITLE
int(final_cfs_sparse.at[cf_ix, feature]) in do_posthoc_sparsity_enhancement, do_linear_search and do_binary_search

### ISSUE THREAD

**Issue by azz147** [interpretml/DiCE#342]
When performing `do_posthoc_sparsity_enhancement`, the code calculates the difference between `final_cfs_sparse` and `query_instance` by doing
https://github.com/interpretml/DiCE/blob/d176e120c54f481d43de91a9b04904c1d1df1f65/dice_ml/explainer_interfaces/explainer_base.py#L535
I don't understand why the code uses `int` here. From the paper I think the code should be 
```diff = query_instance[feature].iat[0] - final_cfs_sparse.at[cf_ix, feature]```

In `do_linear_search` and `do_binary_search` the code also converts the `final_cfs_sparse` value to integer before calculating `diff`.

Before the commit b1f55baf756dd7d52f14f508cb86ea0116af1fb1, the code didn't take the integer value of `final_cfs_sparse`. I cannot find the reason from commit message.

Could you please let me know whether this is expected behavior?

**Comment by amit-sharma** [comment]
thanks @azz147 for catching this. This looks like a bug, and not sure why the `int` was added. 
Would you like to raise a PR to fix this? I see the `int(` typecast in multiple places in explainer_base.py.
