### ISSUE TITLE
load_adult_income_dataset returns FileNotFoundError

### ISSUE THREAD

**Issue by tongyu-microsoft** [interpretml/DiCE#374]
Run the following commands:
`from dice_ml.utils import helpers`
`helpers.load_adult_income_dataset()`

Get error FileNotFoundError:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\lib\site-packages\numpy\lib\npyio.py", line 1934, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "...\site-packages\numpy\lib\_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: http://archive.ics.uci.edu/static/public/2/adult.data not found.

**Comment by gaugup** [comment]
This has been fixed in the PR https://github.com/interpretml/DiCE/pull/373. The fix is pending a release of dice-ml.
