### ISSUE TITLE
pip install dice downloads tests

### ISSUE THREAD

**Issue by johnHostetter** [interpretml/DiCE#385]
Hello, 

After executing pip install dice, DiCE's tests override my project's test folder. 

Steps to reproduce:
1. Make a project with a tests folder
2. pip install dice
3. Make two test files in tests\, one that defines some function (e.g., `make_example`) and another that imports that function:
`from tests.rough.krs import make_example`
4. Run tests; see Exception: `ModuleNotFoundError: No module named 'tests.rough' `

It seems the tests are being installed through pip. Can this be fixed? 

https://github.com/interpretml/DiCE/blob/e9e7147fce95b09de2f38d21cf59e0031dee28ae/setup.py#L32

I think  `tests*`  may need to be changed to simply `tests`.

Thank you for your time.

**Comment by gaugup** [comment]
@johnHostetter, The PR https://github.com/interpretml/DiCE/pull/382 has not been released as yet. Shouldn't this PR fix the issue?

**Comment by johnHostetter** [comment]
> @johnHostetter, The PR #382 has not been released as yet. Shouldn't this PR fix the issue?

Yes, my apologies. I must have overlooked the pull request. Thank you so much for addressing this issue and for your great work in providing us with this library! I intend to use it in some upcoming research if all goes according to plan (with appropriate citations for this work, of course 😄).
