### ISSUE TITLE
Getting AttributeError: module 'tensorflow' has no attribute 'get_default_session'

### ISSUE THREAD

**Issue by prakharrathi25** [interpretml/DiCE#39]
I tried to run DICE with a pretrained XGBoost model and ran into this error. `AttributeError: module 'tensorflow' has no attribute 'get_default_session'()`. I am using TensorFlow version 2.3.0. Seems to be an issue with the version. Is there a fix for this?

**Comment by raam93** [comment]
Yes, you need to provide appropriate value for the `backend` variable when you create a DiCE model object - please see section "Loading the ML model" of this notebook: https://github.com/interpretml/DiCE/blob/master/docs/source/notebooks/DiCE_getting_started.ipynb. 

However, DiCE currently supports sequential models based on TensorFlow and PyTorch frameworks only. TF has its own BoostedTreeClassifier however the estimator API is too abstract for the current DiCE implementation. DiCE works only when a model object is callable but the estimator does not support that and instead has train() and evaluate() methods.

This feature has been of interest to many (https://github.com/interpretml/DiCE/issues/10) and we are working on it. Meanwhile, feel free to contribute if you have any ideas. Thanks!
