### ISSUE TITLE
Infinite loop in specific conditions

### ISSUE THREAD

**Issue by rmazzine** [interpretml/DiCE#46]
https://github.com/interpretml/DiCE/blob/a772c8d4fcd88d1cab7f2e02b0bcc045dc0e2eab/dice_ml/explainer_interfaces/explainer_base.py#L73

The post-hoc sparsity enhancement can enter in an infinite loop in certain conditions (I tested with all numerical data, with data ranging, mostly, from -1 to 1). If you need, I can attach here the data. The cause is, for small numbers, sometimes the rate of change is very small or even zero, then, it stucks in this step.

I think one possible solution is to check the difference between the new `diff` and old difference  `old_diff`, something like:

```python
        if (old_diff == diff) or ((old_diff-diff) < 1e-5):
            n_tolerance += 1
        else:
            n_tolerance = 0
```

and adding another stop condition on the `while` loop: `n_tolerance <= max_tolerance`

**Comment by raam93** [comment]
Yes, that's a good catch! Indeed, it gets stuck in an infinite loop for values much lower than zero. However, the default sparsity correction method that you are using performs a linear search. If the option `posthoc_sparsity_algorithm` in `generate_counterfactuals()` is changed to "binary", which performs a binary search instead, the results are much faster. We have observed the binary option work well in practice with few real-world datasets. Can you try it and let me know how it goes?

That said, for the linear method, I really like your suggestion! Can you please raise a PR on the same?

**Comment by raam93** [comment]
We will add a note about different methods in sparsity enhancement in the notebooks too.

**Comment by rmazzine** [comment]
Hello! 

I made a notebook on colab to reproduce this bug, and it does not even need to have a low value (as demonstrated by this example).

https://colab.research.google.com/drive/1vIJ79cV1WmNAl2usZJIBNIxdcFQn3H_h?usp=sharing

I will open a PR with my suggested solution soon then!

**Comment by tonyabracadabra** [comment]
> Hello!
> 
> I made a notebook on colab to reproduce this bug, and it does not even need to have a low value (as demonstrated by this example).
> 
> https://colab.research.google.com/drive/1vIJ79cV1WmNAl2usZJIBNIxdcFQn3H_h?usp=sharing
> 
> I will open a PR with my suggested solution soon then!

Hey Raphael, it's been a while now, do you mind revisiting this issue and open the PR for it?

**Comment by rmazzine** [comment]
Surely! I will make a reproducible code for the error again first, then, make the necessary modifications.

**Comment by tonyabracadabra** [comment]
> Surely! I will make a reproducible code for the error again first, then, make the necessary modifications.

Thanks Raphael

**Comment by rmazzine** [comment]
Sorry for the late response!

Here's the updated notebook reproducing the problem:
https://colab.research.google.com/drive/1vIJ79cV1WmNAl2usZJIBNIxdcFQn3H_h?usp=sharing

I think the solution can be simpler. From my tests, the linear search should not take more than 10k steps. Therefore, just adding a counter and establishing an upper limit is sufficient.

You can see this change in this commit: https://github.com/rmazzine/DiCE/commit/22f2c12d822a7bcb26a5b1f169e601b217c022cb 

And in this notebook below you can see it fixes the problem:
https://colab.research.google.com/drive/1W6nlXucrure8hNwQ2bByjxdlxmtF-i3r?usp=sharing

This PR (https://github.com/interpretml/DiCE/pull/293) does that. Therefore, I implement an additional condition for the number of steps that can be changed by the user by modifying the parameter `limit_steps_ls`.
