### ISSUE TITLE
dice-ml pip install uses older version of scipy

### ISSUE THREAD

**Issue by taposh** [interpretml/DiCE#49]
While running 
`d = dice_ml.Data(dataframe=dataset, continuous_features=['age', 'hours_per_week'], outcome_name='income')
`
I get an error 
```
---> 25 from scipy.misc import comb
     26 from ..utils import indexable, check_random_state, safe_indexing
     27 from ..utils.validation import _num_samples, column_or_1d

```
ImportError: cannot import name 'comb'

This has been depreciated
`from scipy.misc import comb `

update needed

`from scipy.special import comb 
`
https://docs.scipy.org/doc/scipy-1.2.1/reference/generated/scipy.misc.comb.html

**Comment by raam93** [comment]
Hi @taposh, I just checked `pip install dice-ml` and it works just fine on my Windows machine. Are you sure you are using the latest DiCE version which is v0.4 (https://pypi.org/project/dice-ml/)? If so, could you share the versions of DiCE's dependencies?

**Comment by amit-sharma** [comment]
Closing this issue. I hope the new version resolved this problem @taposh [our current version is 0.5]
