### ISSUE TITLE
Why use the MAD in normalized features?

### ISSUE THREAD

**Issue by wangyongjie-ntu** [interpretml/DiCE#54]
The MAD is mainly for the heterogeneous features(different features have different scales, ranges).
If you normalize the features with a min-max scaler. all features are mapped into [0,1]. 

In the adult example, the data interface normalizes the features, why does the defaulted setting is "inverse_mad"?  From my understanding,  the l2 distance is good. The paper "COUNTERFACTUAL EXPLANATIONS WITHOUT
OPENING THE BLACK BOX: AUTOMATED DECISIONS AND THE GDPR"  P18, Equation 5, the authors also suggest the l2 distance. 

Do you find any differences between these two kinds of distance ？

**Comment by raam93** [comment]
You are correct in the interpretation of MAD however you missed the fact that the distribution of features after min-max scaling stays the same. Any scaling method will not change the shape of the data distribution but changes only the range. So dividing the distance by MAD (inverse_mad option) is to capture the relative prevalence of observing the feature at a particular value. Please refer to sec 3.3 "Choice of distance function." in our [paper](https://arxiv.org/pdf/1905.07697.pdf) or refer to the paragraph below equation 4 in [Wachter et al paper](https://arxiv.org/pdf/1711.00399.pdf). However, I agree that you could use l2 distance scaled by standard deviation or any other variant, but we found the l1-MAD option working well for most scenarios in our experiments. Anyways, we will include more options for distance loss soon.

Meanwhile, in the Wachter et al. paper, the authors do not suggest to use l2-distance always, but instead they experiment with different variants of distance functions and even show that l1-MAD option generates sparser results (last para of LSAT data section, [P20](https://arxiv.org/pdf/1711.00399.pdf)).
